proj:
  name: bee
  description: bee is a project automation tool written in PHP
  type: php/app
  commands:
    test:
      unit: "lime:test"
      plugins: "bee:test-plugin"
      functional: "lime:test"
      all: ["test:unit", "bee:test-plugin"]
      prova: "shell:execute"
    cpp:
      build: "shell:execute"
  bee:  # bee extra configuration keys
    plugins: ~
  repository:
    type: git
  shell:
    aliases:
      alias1: echo "you called alias1"
      dir-lin: dir --help
      dir-win: dir /?
