nb_lib_dir: "<?php echo nbConfig::get('nb_bee_dir','.').'/'; ?>lib"
nb_command_dir: "<?php echo nbConfig::get('nb_bee_dir','.').'/'; ?>lib/command"
nb_test_dir: test/unit
nb_project_config: project.yml
